version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: mxssl/revolut-sre-test-task
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_NAME: app
      DB_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
